### ISSUE TITLE
Change Password is limited to 12 characters

### ISSUE THREAD

**Issue by maxdev429** [overhold-org/Overhold-Wallet#11]
The field to enter the new password is limited to 12 characters. This does not seem very secure to me and should probably be changed.

**Comment by blag0j** [comment]
@bolecoin , thanks for the notice - we should probably make an adjustment for this and allow more characters. However, it is not a bug but a possible improvement. 

It is not a security issue, because the password is stored locally and is used as another layer of protection. Possibility of someone guessing or brute forcing your password is very small and reduced to the users that are using your machine. The intended wallet use case is to be used from personal computer.

**Comment by blag0j** [comment]
@maxdev429 This issue has been fixed with the latest updates in the develop branch. The release will be published in the following days.
