### ISSUE TITLE
Coin settings

### ISSUE THREAD

**Issue by CaptainSkywave** [overhold-org/Overhold-Wallet#13]
Settings > Coins
MAID will not display on Home and Price w/o OMNI
If deselecting OMNI and selecting MAID (green icon) - Home and Price does not show MAID - when going back to Coins - MAID has reverted to deselected (red)

**Comment by blag0j** [comment]
Hi @CaptainSkywave, thanks for your notice, but all of the mentioned stuff is normal, because:

1. Maid and Omni are not displayed on the Home page at the current stage of the wallet development, because we support them only in explorer view currently (only prices and charts for them are displayed).
2. Data for Maid is dependent on Omni blockchain, and is unreasonable to have Omni disabled and to have Maid working. When you disable Omni, then the Omni blockchain is disabled (where data for Maid is pulled from as well), and thus Maid gets disabled automatically as well. I've explained this in the following issue as well: https://github.com/overhold-org/Overhold-Wallet/issues/5

I am closing this, because it is neither bug or feature request but a misunderstanding about the wallet functionalities. If you have some more questions, please re-open it.
