### ISSUE TITLE
Tab 'Home' Spelling Mistake

### ISSUE THREAD

**Issue by AwesomeVinc** [overhold-org/Overhold-Wallet#18]
![image](https://user-images.githubusercontent.com/31467087/48551503-98754f80-e93a-11e8-9614-deba44ce6e66.png)

I believe it should display 'WAVES' instead of 'WAVE'.

Recommendation: Use 2 decimals for displaying the Waves Price. It's more satisfying for the eyes.

**Comment by blag0j** [comment]
According to the standards WAVES is the currency code for the Waves cryptocurrency, so it should be displayed instead of WAVE - it will be changed (it was cut to WAVE, because probably WAVES seemed to be too long).

About the number of decimals for the number display-  it is handled by the language itself, but we will consider your recommendation for two decimals to be the minimum number of decimals for display.

**Comment by blag0j** [comment]
@AwesomeVinc This issue has been fixed with the latest updates in the develop branch. The release will be published in the following days.
