### ISSUE TITLE
Second login not working

### ISSUE THREAD

**Issue by AwesomeVinc** [overhold-org/Overhold-Wallet#2]
System used: 64-bit | Windows 10 Home

The first sign up works like a charm. Closing the wallet and restarting it brings the problems. 
Neither signing into the account nor registering a new account is possible. The button triggering the execution turn grey and stays grey after pressing it. 

For first time users it would be useful to navigate them to create the mnemonic passphrase, so if they loose any credential (username or password), they can easily recover it rather than having problems in the future.

**Comment by blag0j** [comment]
@AwesomeVinc thanks for the explanation. About the mnemonic, it is automatically created when you register a new account. You can view the created mnemonic (and back it up) at the Backup Wallet page.
You should be able to use this mnemonic in the future, if you want to recover (basically to generate the same data) at Overhold wallet, or if you want to import the data in another wallet (the wallets that support the recover/import from mnemonic feature).

Regarding the issue, could you give use more details if you're running the program as an Administrator, and also if you're running the main bundled executable or the executable found in the unpacked directory?

**Comment by blag0j** [comment]
@AwesomeVinc apparently there are issues with generating and accessing the local databases which the wallet needs for it to run properly. 

The main .exe version is the bundled version which is the portable version of the whole app, that's why it takes a bit more to load. We can change the installation process for windows as well in the future.

We also haven't tested on a 32 bit OS versions yet, currently only 64 bit  versions are supported.

This issues is very similar to the one @bolecoin reported. We will have more details about the issue and hopefully we will get it fixed as soon as possible.

**Comment by CaptainSkywave** [comment]
..I've done the same - using the .exe inside the unpacked folder.
Login turns greay and notheing happens.
12 word mnemonic turns grey.
Nothing happens

**Comment by CaptainSkywave** [comment]
..ofcourse, I just tried again - as admin - Log in worked instantly

**Comment by blag0j** [comment]
@AwesomeVinc , @CaptainSkywave this bug is fixed in the newest 1.0.1 release.

I am closing this issue because it is not present anymore in the latest release.
